apiKey: "AIzaSyBHXUu-oaBHd94QDzNgHWtP8KfEnGUhkEY"
authDomain: "dcbl-test.firebaseapp.com"
databaseURL: "https://dcbl-test.firebaseio.com"
projectId: "dcbl-test"
storageBucket: "dcbl-test.appspot.com"
messagingSenderId: "129224597683"
appId: "1:129224597683:web:61f5b19413bb0a0ff9d0c6"
rsvpIdURL: "https://europe-west2-dcbl-test.cloudfunctions.net/authenticate?id="